"""Build MMS with this Python interpreter; all versions come from core.

    python -X utf8 packaging/build.py --sync-version
    python -X utf8 packaging/build.py --no-installer
"""
import argparse
import importlib.util
import os
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from core import __version__


def sync_version():
    parts = tuple(int(p) for p in __version__.split("."))
    if len(parts) != 3:
        raise ValueError("Use a three-component release version in core/__init__.py")
    ffi_version = (*parts, 0)
    text = f"""# Generated by packaging/build.py from core.__version__.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={ffi_version!r}, prodvers={ffi_version!r}, mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('0C0A04B0', [
      StringStruct('CompanyName', 'bmnigom'),
      StringStruct('FileDescription', 'Adquisición MMS - registro IMU y pruebas funcionales'),
      StringStruct('FileVersion', '{__version__}'),
      StringStruct('InternalName', 'AdquisicionMMS'),
      StringStruct('OriginalFilename', 'AdquisicionMMS.exe'),
      StringStruct('ProductName', 'Adquisición MMS'),
      StringStruct('ProductVersion', '{__version__}')])]),
    VarFileInfo([VarStruct('Translation', [0x0C0A, 1200])])
  ]
)
"""
    (ROOT / "packaging/version_info.txt").write_text(text, encoding="utf-8")
    (ROOT / "packaging/app_version.iss").write_text(
        f'; Generated by packaging/build.py.\n#define AppVersion "{__version__}"\n', encoding="utf-8")


def run(args, *, timeout=300):
    print("RUN", " ".join(str(a) for a in args), flush=True)
    subprocess.run([str(a) for a in args], cwd=ROOT, check=True, timeout=timeout)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sync-version", action="store_true")
    parser.add_argument("--no-installer", action="store_true")
    parser.add_argument("--skip-check", action="store_true")
    args = parser.parse_args()
    sync_version()
    if args.sync_version:
        print(f"VERSION_OK {__version__}")
        return
    for dependency in ("PyInstaller", "numpy", "PyQt6", "pyqtgraph", "mbientlab.metawear", "mbientlab.warble"):
        if importlib.util.find_spec(dependency) is None:
            parser.error(f"Missing {dependency} in {sys.executable}; install requirements-dev.txt with this interpreter.")
    run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--distpath", "dist", "--workpath", "build", "packaging/MMS.spec"])
    if not args.skip_check:
        run([ROOT / "dist/AdquisicionMMS/AdquisicionMMS.exe", "--check"], timeout=30)
    if not args.no_installer:
        candidates = [Path(os.environ.get("LOCALAPPDATA", "")) / "Programs/Inno Setup 6/ISCC.exe",
                      Path(os.environ.get("ProgramFiles(x86)", "C:/Program Files (x86)")) / "Inno Setup 6/ISCC.exe"]
        compiler = next((p for p in candidates if p.is_file()), None)
        if compiler:
            run([compiler, ROOT / "packaging/instalador.iss"])
        else:
            print("Inno Setup no está instalado. Ejecutable disponible en dist/AdquisicionMMS.")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        sys.exit(exc.returncode)
